version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/scholarships
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: scholarship_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
